export const permissions = [
    {
        role: 'user',
        actions: [
            {
    role: 'vendor',
    actions: [
        'get_profile',
        'update_profile',
        'add_products',
        'view_product',
        'view_products',
        'update_product',
        'delete_product',
        'delete_products',
        'manage_own_products',
        'manage_waste_pickups',
        'get_history',
        'get_users_products',
        'send_message_to_admin',
        'get_users_stats',
        'view_leaderboard',
        'get_users_schedules',
        'schedule_pickup',
        'delete_schedule',
    ]
},
        ]
    },
    {
        role: 'vendor',
        actions: [
            'get_profile',
            'update_profile',
            'add_products',
            'view_product',
            'view_products',
            'update_product',
            'delete_product',
            'delete_products',
            'manage_own_products',
            'manage_waste_pickups',
            'get_history',
            'get_users_products',
            'send_message_to_admin',
            'get_users_stats',
            'view_leaderboard',
            'get_users_schedules',
            'schedule_pickup',
            'delete_schedule',
        ]
    },
    {
        role: 'admin',
        actions: [
            'get_all_profiles',
            'manage_all_products',
            'manage_users',
            'view_all_pickups',
            'get_history',
            'update_pickup_status',
            'receive_messages',
            'delete_schedule',
            'update_product',
            'delete_product',
            'delete_products',
            'get_profile',
            'update_profile',
            'add_products',
            'view_product',
            'view_products',
            'get_users_stats',
            'view_leaderboard',
            'get_users_schedules',
            'get_users_products',
            'assign_agent',
            'manage_agents',
            'view_platform_stats',
        ]
    }
];